### PR TITLE
add option to remove HTML tags from descriptions

### PR DESCRIPTION
**Pull request by genjohnson**
This PR addresses issue #12

### CODE REVIEW

**Comment by brandonneil** [comment]
It looks like the default branch was master, so this PR is targeted to that. I just changed it to 7.x-1.x so this will need to be targeted to that branch.

**Comment by brandonneil** [comment]
Also, sites already using this pane will have $conf['plain_text'] undefined for each instance of the page. You will want to either wrap at in a !empty() or in an update hook add the plain_text default configuration to each type -> academic_date_list row in the panels_pane table.

**Comment by genjohnson** [comment]
@brandonneil, @richardbporter - I've added an update hook per Brandon's comment and changed the base branch to 7.x-1.x. Could you give this another review?

**Comment by richardbporter** [comment]
Something like cd079f4 would prevent the notice. I don't know if the update hook is necessary then.

Otherwise, I tested the plain text option on a couple panes and it works great.

**Comment by richardbporter** [comment]
>  I don't think the update hook is necessary then.

Its certainly not hurting anything.

**Pull request merged**
